userName=input("what is your name:")
food=input("what is your favorite food:")
music=input("what is your favorite music:")
address=input("what is your address:")
print("your name is:",userName)
print("your favorite food is:",food)
print("your favorite music is:",music)
print("your address is:",address)
print(" living in the amazing Edge of reality")